version: '3'

services:
  api:
    build: ./api
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["gunicorn", "-b", "0.0.0.0:5002", "app.main:create_app()"]
    networks:
      - api_webnet

networks:
  api_webnet:
    external: true
