version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app.main:create_app()"]

